### ISSUE TITLE
Rotate docker logs.

### ISSUE THREAD

**Issue by vigliensoni** [lingxiaoyang/Tension-Analysis#8]
We need to implement some kind of rotation of Docker logs, otherwise, they eat all the disk space and eventually the app crashes.

Since we are using docker compose, it seems the proper way of doing this would be to set it in the docker-compose.yml configuration file.

Perhaps:

```
my-app:
    image: my-app:latest
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
```
